### ISSUE TITLE
Documentation missing link to Postman collection

### ISSUE THREAD

**Issue by bjacobel** [SanaMobile/sana.mds#1]
Hi there,

The documentation at [this link](http://sana.mit.edu/mobile/documentation/developers/middleware/mds-rest-api/#user-content-browser-based-client) references a Postman collection that can be used to explore the Sana MDS API, but the link to the collection is missing.

Thanks!

**Comment by ewinkler** [comment]
Thanks for letting us know. I will get it posted as soon as I am able-travelling this week so it may be early next before I have a chance.

**Comment by ewinkler** [comment]
The missing postman file has been uploaded and missing link added to the [online doc](http://sana.mit.edu/mobile/documentation/developers/middleware/mds-rest-api/#user-content-browser-based-client)

Direct link:
http://demo.sana.csail.mit.edu/downloads/mds2/mds2.json

**Comment by bjacobel** [comment]
Thanks!
