### ISSUE TITLE
Bad Request (400) 

### ISSUE THREAD

**Issue by endangurura** [SanaMobile/sana.mds#7]
I'm getting this error on a fresh install of sana.mds on Ubuntu 14.04 LTS GCE instance.

`[Wed Nov 23 06:12:50.695406 2016] [:error] [pid 12683] /usr/lib/python2.7/dist-packages/piston/handler.py:27: UserWarning: Handler already registered for model Event, you may experience inconsistent results.
[Wed Nov 23 06:12:50.695433 2016] [:error] [pid 12683]   "you may experience inconsistent results." % new_cls.model.__name__)
[Wed Nov 23 06:12:50.695435 2016] [:error] [pid 12683]`

Can somebody help me to fix this.

Thanks,

Emmauel

**Comment by ewinkler** [comment]
The Handler warning is something that needs to be removed but isn't the source of the 400 response. It seems like something may have been updated in one of the Ubuntu packages that requires defining  ALLOWED_HOSTS in the mds.settings file. The link below is for Django 1.7 but explains what appears to be the source of the issue.
[ALLOWED_HOSTS] (https://docs.djangoproject.com/en/1.7/ref/settings/#allowed-hosts)

**Comment by endangurura** [comment]
That one I figured it out. ALLOWED_HOST=[] is what was missing.

**Comment by ewinkler** [comment]
I am going to close this one then.
